### ISSUE TITLE
Phantom Action gets generated when testing effect

### ISSUE THREAD

**Issue by rrennie6** [ngrx/platform#1105]
## Minimal reproduction of the bug/regression with instructions:
Upon running the effect test for the code given below, I get the following error:
```
Expected $.length = 2 to equal 1.
Expected $[1] = Object({ frame: 0, notification: Notification({ kind: 'C', value: undefined, error: undefined, hasValue: false }) }) to equal undefined.
	    at TestScheduler.deepEqual [as assertDeepEqual] (webpack:///spec/support/rxjs_helper.ts:7:67 <- config/karma-test-shim.js:177075:73)
	    at TestScheduler.flush (webpack:///node_modules/rxjs/testing/TestScheduler.js:118:0 <- config/karma-test-shim.js:129799:18)
	    at Object.exports.runMarbleTest (webpack:///spec/support/rxjs_helper.ts:22:14 <- config/karma-test-shim.js:177083:15)
	    at UserContext.<anonymous> (webpack:///spec/effects/shared/user_options/vehicle_field_user_option.spec.ts:32:6 <- config/karma-test-shim.js:193642:27)
```

It is showing that there is an extra action in the list with a value of undefined. I traced it through the TestScheduler code, and it appears that the VirtualTestScheduler.schedule method is called when I create my cold observable and again when I call expectObservable. The first time, it adds my "Load" action to the list of actions as expected. However, the second time (when I call expectObservable), the VirtualTestScheduler.schedule method adds another action to the list with undefined state, causing my test to fail. Let me know if there is something I'm missing here. I'm fairly certain it should not create another action that I did not specify in the marbles.

Also, the code itself works appropriately in the application, and I believe that the actual part I am testing works and gets set as the first index of "Expected." It is just this random action being added that causes the test to fail. This test used to pass before upgrading to ngrx 4. The major changes I made are in the setup. I did not change rxjs_helper.ts at all when upgrading.

Setup (ngrx_setup.ts):
```
import * as ngrx from '@ngrx/store';
import {Store, combineReducers} from '@ngrx/store';
import {Actions} from '@ngrx/effects';
import {reducers, State} from '../../src/reducers';
import {Observable} from 'rxjs/Observable';

export const initialStateFactory = (): State =>
  combineReducers(reducers)(undefined, { type: ngrx.INIT });

export const ngrxSetup = (action?: any): {store: Store<State>, actions: Actions} => {
  const initialState = initialStateFactory();
  const reducerObs = Observable.of(combineReducers(reducers));
  const actions = action ? new Actions(Observable.of(action)) : new Actions();
  const actionsSubject = new ngrx.ActionsSubject();
  const reducerManager = new ngrx.ReducerManager(actionsSubject, initialState, reducers, combineReducers);
  const stateObs = new ngrx.State(actionsSubject, reducerObs, new ngrx.ScannedActionsSubject(), initialState);
  const store: Store<State> = new ngrx.Store<State>(stateObs, actionsSubject, reducerManager);
  return {store, actions};
};
```

Test (vehicle_field_user_option.spec.ts):
```
import {Observable} from 'rxjs/Observable';
import * as vehicleFieldUserOptionActions from '../../../../src/actions/shared/user_options/vehicle_field_user_option';
import {ngrxSetup} from '../../../support/ngrx_setup';
import {runMarbleTest} from '../../../support/rxjs_helper';
import {SetAllVehicles} from '../../../../src/actions/inventory/vehicle/vehicle';
import {List} from 'immutable';
import {VehicleFieldUserOptionEffects} from '../../../../src/effects/shared/user_options/vehicle_field_user_option';

const mockService = {
  getUserOptions: (): Observable<{ [key: string]: boolean }> => {return Observable.empty(); }
};

describe('VehicleFieldUserOptionEffects', () => {
  describe('loadEffect', () => {
    it('loads the user options', () => {
      const {store, actions} = ngrxSetup(new vehicleFieldUserOptionActions.Load());
      const effects = new VehicleFieldUserOptionEffects(actions, mockService);
      const observable = effects.loadUserOptions();
      const response: { [key: string]: boolean } = {'field': true};
      const vehicleFieldUserOptionServiceSpy = spyOn(mockService, 'getUserOptions')
        .and.returnValue(Observable.of(response));

      const actionMap = {
        a: new SetAllVehicles({savedVehicles: List()}),
        b: new vehicleFieldUserOptionActions.Load()
      };
      const outputMap = {
        a: new vehicleFieldUserOptionActions.LoadSuccess({userOptions: response})
      };
      const inputs = 'b';
      const outputs = 'a';
      runMarbleTest(store, observable, actionMap, outputMap, inputs, outputs);
      expect(mockService.getUserOptions).toHaveBeenCalled();
    });
  });
});
```

Test Helper (rxjs_helper.ts):
```
import {Action, Store} from '@ngrx/store';
import {TestScheduler as TScheduler} from 'rxjs/testing/TestScheduler';
import {Observable} from 'rxjs/Observable';
import {State} from '../../src/reducers';

export const TestScheduler = (): TScheduler => {
  const deepEqual = (actual: any, expected: any) => expect(actual).toEqual(expected);
  return new TScheduler(deepEqual);
};

export const runMarbleTest = (
  store: Store<State>,
  observable: Observable<any>,
  actionMap: Object,
  outputMap: Object,
  inputs: string,
  outputs: string): void => {
    const scheduler = TestScheduler();
    const stimulus: Observable<Action> = scheduler.createColdObservable(inputs, actionMap);
    stimulus.subscribe(action => { store.dispatch(action); });
    scheduler.expectObservable(observable).toBe(outputs, outputMap);
    scheduler.flush();
  };
```

Actual Effect (vehicle_field_user_option.ts):
```
import {Injectable, Inject} from '@angular/core';
import {Effect, Actions} from '@ngrx/effects';
import {Action} from '@ngrx/store';
import {Observable} from 'rxjs/Observable';
import * as vehicleFieldUserOptionActions from '../../../actions/shared/user_options/vehicle_field_user_option';
import {
  VehicleFieldUserOptionServiceToken,
  IVehicleFieldUserOptionService
} from '../../../services/user_options/vehicle_field_user_option_service';

@Injectable() export class VehicleFieldUserOptionEffects {
  constructor(
    private actions: Actions,
    @Inject(VehicleFieldUserOptionServiceToken) private vehicleFieldUserOptionService: IVehicleFieldUserOptionService,
  ) { }

  @Effect() loadUserOptions = (): Observable<Action> =>
    this.actions
      .ofType(vehicleFieldUserOptionActions.LOAD)
      .mergeMap(this.callService)
      .map(this.handleResponse)

  private readonly callService = (): Observable<{ [key: string]: boolean }> => {
    return this.vehicleFieldUserOptionService.getUserOptions();
  }

  private readonly handleResponse =
    (response: { [key: string]: boolean }): vehicleFieldUserOptionActions.LoadSuccess => {
    return new vehicleFieldUserOptionActions.LoadSuccess({userOptions: response});
  }
}
```

## Expected behavior:
The test should only fire the load action and see that the load success action is returned from the effect.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
@ngrx/effects: 4.0.5
@ngrx/store: 4.0.3
@ngrx/store-devtools: 4.0.0
angular: 4.4.7
npm: 4.0.5

**Comment by tdeschryver** [comment]
Hi, do you got a repro for this? 
I can't quite figure out what might be wrong by looking at the code, I tried to reproduce it but I kept bumping into other stuff...

Did you also update RxJs? 
Because if  `TestScheduler`  is causing the problem, it should maybe be addressed there.
I also came across [https://github.com/kwonoj/rxjs-testscheduler-compat](https://github.com/kwonoj/rxjs-testscheduler-compat) if this helps...

**Comment by rrennie6** [comment]
Sorry for making it difficult for you. Below is the issue reproduced all in one file so you don't have to go through that mess. I couldn't share the repo because it is not open source. Also, I am using rxjs 5.5.10 so I believe it should be compatible.

```
import {Observable} from 'rxjs/Observable';
import * as ngrx from '@ngrx/store';
import {Action, Store, combineReducers} from '@ngrx/store';
import {Injectable} from '@angular/core';
import {Effect, Actions} from '@ngrx/effects';
import {TestScheduler as TScheduler} from 'rxjs/testing/TestScheduler';
import {ActionReducerMap} from '@ngrx/store';

interface State { }
const reducers: ActionReducerMap<State> = { }

const LOAD = '[Shared VehicleFieldUserOption] Load';
const LOAD_SUCCESS = '[Shared VehicleFieldUserOption] Load Success';

interface LoadSuccessPayload {
  userOptions: { [key: string]: boolean };
}

class Load implements Action {
  readonly type = LOAD;
}

class LoadSuccess implements Action {
  readonly type = LOAD_SUCCESS;
  constructor(public payload: LoadSuccessPayload) { }
}

@Injectable() class TestSchedulerTestEffects {
  constructor(private actions: Actions) { }

  @Effect() effect = (): Observable<Action> =>
    this.actions
      .ofType(LOAD)
      .map(this.handleResponse)

  private readonly handleResponse = (): LoadSuccess => {
    return new LoadSuccess({userOptions: {}});
  }
}

const TestScheduler = (): TScheduler => {
  const deepEqual = (actual: any, expected: any) => expect(actual).toEqual(expected);
  return new TScheduler(deepEqual);
};

describe('TestSchedulerTestEffects', () => {
  describe('effect', () => {
    fit('load action calls load effect', () => {
      const action = new Load();

      const initialState = combineReducers(reducers)(undefined, { type: ngrx.INIT });
      const reducerObs = Observable.of(combineReducers(reducers));
      const actions = action ? new Actions(Observable.of(action)) : new Actions();
      const actionsSubject = new ngrx.ActionsSubject();
      const reducerManager = new ngrx.ReducerManager(actionsSubject, initialState, reducers, combineReducers);
      const stateObs = new ngrx.State(actionsSubject, reducerObs, new ngrx.ScannedActionsSubject(), initialState);
      const store: Store<State> = new ngrx.Store<State>(stateObs, actionsSubject, reducerManager);

      const effects = new TestSchedulerTestEffects(actions);
      const observable = effects.effect();

      const actionMap = {
        a: new Load()
      };
      const outputMap = {
        a: new LoadSuccess({userOptions: {}})
      };
      const inputs = 'a';
      const outputs = 'a';

      const scheduler = TestScheduler();
      const stimulus: Observable<Action> = scheduler.createHotObservable(inputs, actionMap);
      stimulus.subscribe(act => { store.dispatch(act); });
      scheduler.expectObservable(observable).toBe(outputs, outputMap);
      scheduler.flush();
    });
  });
});
```

**Comment by tdeschryver** [comment]
Thanks it helped!
You should `flush` before testing the expected output, so it becomes:

```
scheduler.flush();
scheduler.expectObservable(observable).toBe(outputs, outputMap);
```

(based on the rxjs [spec](https://github.com/ReactiveX/rxjs/blob/6ebc565d05eff5bf20bfc0f77feba4b099d51f82/spec/schedulers/TestScheduler-spec.ts)

**Comment by rrennie6** [comment]
As nice as that may seem, though it makes the test pass, it also makes it a false positive. No matter how you change the expected outputs it will still pass in that case. I do not see an example of this in the link you posted unless I am missing something. I would just as well open an issue with them, but I am here because ngrx is the only thing I upgraded.

**Comment by tdeschryver** [comment]
Oops you're right  :sweat_smile:
I think I won't be able to help you then.
But I believe that the phantom action isn't just a phantom action tho, it's notifying that it's been completed
- [RxJs notification docs](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/notification.md#kind).

So I believe this is working as intended.

**Comment by rrennie6** [comment]
You are right. It was working as intended but is just surprising. I found it odd that the store was no longer required in testing effects. To whoever it may concern, the reason it was giving a "complete" action at the end was because of how I was passing my inputs. I did not realize that in the inputs were actually being driven off of this line:
`const actions = action ? new Actions(Observable.of(action)) : new Actions();`

rather than these:
```
const stimulus: Observable<Action> = scheduler.createHotObservable(inputs, actionMap);
stimulus.subscribe(act => { store.dispatch(act); });
```

The "Actions" class in the new ngrx is what has unexpected behavior I think. You can pass it either one action or a cold observable based on a set of inputs and an input map. If you pass it an action, **apparently it also sends a "complete" action afterward by default**. However, if you pass it a cold observable (for example my "stimulus" above), then it obeys those inputs and does not send a "complete" action afterward by default. The working code in one file is given below with the major change being creating the effect with the stimulus, and it is much cleaner too. Feel free to close this unless you have any final comments. Thank you for your help!

```
import {Observable} from 'rxjs/Observable';
import {Action, Store} from '@ngrx/store';
import {Injectable} from '@angular/core';
import {Effect, Actions} from '@ngrx/effects';
import {TestScheduler as TScheduler} from 'rxjs/testing/TestScheduler';
import {ActionReducerMap} from '@ngrx/store';

const LOAD = '[Shared VehicleFieldUserOption] Load';
const LOAD_SUCCESS = '[Shared VehicleFieldUserOption] Load Success';

interface LoadSuccessPayload {
  userOptions: { [key: string]: boolean };
}

class Load implements Action {
  readonly type = LOAD;
}

class LoadSuccess implements Action {
  readonly type = LOAD_SUCCESS;
  constructor(public payload: LoadSuccessPayload) { }
}

@Injectable() class TestSchedulerTestEffects {
  constructor(private actions: Actions) { }

  @Effect() effect = (): Observable<Action> =>
    this.actions
      .ofType(LOAD)
      .map(this.handleResponse)

  private readonly handleResponse = (): LoadSuccess => {
    return new LoadSuccess({userOptions: {}});
  }
}

const TestScheduler = (): TScheduler => {
  const deepEqual = (actual: any, expected: any) => expect(actual).toEqual(expected);
  return new TScheduler(deepEqual);
};

describe('TestSchedulerTestEffects', () => {
  describe('effect', () => {
    fit('load action calls load effect', () => {
      const actionMap = {
        a: new Load()
      };
      const outputMap = {
        a: new LoadSuccess({userOptions: {}})
      };
      const inputs = 'a';
      const outputs = 'a';

      const scheduler = TestScheduler();
      const stimulus: Observable<Action> = scheduler.createColdObservable(inputs, actionMap);

      const effects = new TestSchedulerTestEffects(new Actions(stimulus));
      const observable = effects.effect();

      scheduler.expectObservable(observable).toBe(outputs, outputMap);
      scheduler.flush();
    });
  });
});
```

**Comment by tdeschryver** [comment]
Glad it has been resolved and for the follow up!
