### ISSUE TITLE
ng-add not found in collection @ngrx/schematics

### ISSUE THREAD

**Issue by testpossessed** [ngrx/platform#1551]
## Minimal reproduction of the bug/regression with instructions:

1. Create new Angular app using 'ng new ngrx-play'
2. Change to new project folder
3. Execute 'ng add @ngrx/store' - no errors
4. Execute 'ng add @ngrx/effects' - no errors
5. Execute 'ng add @ngrx/schematics' - error below

Schematic "ng-add" not found in collection "@ngrx/schematics".
Error: Schematic "ng-add" not found in collection "@ngrx/schematics".
    at SchematicEngine.createSchematic (/Users/mike/_src/ngrx-play/node_modules/@angular-devkit/schematics/src/engine/engine.js:232:23)
    at CollectionImpl.createSchematic (/Users/mike/_src/ngrx-play/node_modules/@angular-devkit/schematics/src/engine/engine.js:69:29)
    at AddCommand.getSchematic (/Users/mike/_src/ngrx-play/node_modules/@angular/cli/models/schematic-command.js:130:27)
    at AddCommand.runSchematic (/Users/mike/_src/ngrx-play/node_modules/@angular/cli/models/schematic-command.js:262:32)
    at AddCommand.executeSchematic (/Users/mike/_src/ngrx-play/node_modules/@angular/cli/commands/add-impl.js:134:31)
    at AddCommand.run (/Users/mike/_src/ngrx-play/node_modules/@angular/cli/commands/add-impl.js:43:25)
    at AddCommand.validateAndRun (/Users/mike/_src/ngrx-play/node_modules/@angular/cli/models/command.js:124:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

## Expected behavior:

I am able to use @ngrx/schematics

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
@angular/cli: 7.3.1
@ngrx:           7.2.0
Node:             10.15.1
OS:                 macOS: Mohave
IDE:                VS Code: 1.31.1 

## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[x ] No

**Comment by testpossessed** [comment]
Reading the documentation again it seems ng add is not supported for @ngrx/schematics.  It seemed an obvious thing to do given the way you setup other ngrx packages.  Closing issue.

**Comment by timdeschryver** [comment]
We got an open issue to support this https://github.com/ngrx/platform/issues/1538
