### ISSUE TITLE
Angular breaks when I install @ngrx/store

### ISSUE THREAD

**Issue by shawmjustin** [ngrx/platform#177]
Steps: 
1. Install angular cli.
2. Create new app, and launch to see that the app is working
3. Install @ngrx/store and try to relaunch the application.... Below is the error you will receive.
angular cli: 1.2.4
node: 8.1.2        
os: win32 x64      
npm - 5.3.0

The "@angular/compiler-cli" package was not properly installed. Error: Error: Cannot find module '@angular/compiler-cli'
Error: The "@angular/compiler-cli" package was not properly installed. Error: Error: Cannot find module '@angular/compiler-cli'
    at Object.<anonymous> (C:\Users\jms219\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@ngtools\webpack\src\index.js:14:11)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\jms219\AppData\Roaming\npm\node_modules\@angular\cli\tasks\eject.js:10:19)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
error Command failed with exit code 1.

**Comment by csutorasr** [comment]
Can you reproduce it in an repo?

**Comment by shawmjustin** [comment]
I just tried to build the ngrx "example-app" (https://github.com/ngrx/example-app) and I am getting permission errors.  I am going to close this issue as I am pretty sure it's related to not having admin rights and being behind my corporate firewall.
