### ISSUE TITLE
Can't build from a path with a space

### ISSUE THREAD

**Issue by ersimont** [ngrx/platform#234]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## What is the current behavior?
`<!-- Describe what the current behavior **would** is. -->`
^^^ First, let me report a copy/paste error in this template (in asterisks above).

Now for the real problem: On Windows, `yarn run build` fails when the project's path has a space in its name:
```
S:\Programming\git repositories\ng-app-state-example>yarn run build
yarn run v0.27.5
$ ts-node ./build/index.ts
× Removing "./dist" Folder
{ Error: Command failed: S:\Programming\git repositories\ng-app-state-example\node_modules\.bin\rimraf ./dist
'S:\Programming\git' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:198:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:497:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'S:\\Programming\\git repositories\\ng-app-state-example\\node_modules\\.bin\\rimraf ./dist' }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Expected behavior:

The project builds.

## Minimal reproduction of the problem with instructions:

1. Clone the project into a directory with a space in its path
1. `yarn install`
1. `yarn run build`.

## Version of affected browser(s),operating system(s), npm, node and ngrx:
- Windows 8.1
- npm 3.10.10
- node 6.11.2
- ngrx master from 1/2 hour ago (2b1a076b1d6308acf7ec96cef6a506574834adc6)

**Comment by ersimont** [comment]
Changing the `exec` function in `build/util.ts` to wrap `base(command)` in quotes got me past the error.  The build still failed later in the process, but I suppose I can open a separate issue for that.  The modified function:

```ts
export function exec(
  command: string,
  args: string[],
  base: BaseFn = fromNpm
): Promise<string> {
  return new Promise((resolve, reject) => {
    cp.exec('"' + base(command) + '" ' + args.join(' '), (err, stdout) => {
      if (err) {
        return reject(err);
      }

      resolve(stdout.toString());
    });
  });
}
```
