### ISSUE TITLE
Example does not run on my system

### ISSUE THREAD

**Issue by creat-or** [ngrx/platform#244]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## What is the current behavior?
I want to run the example, but the build script fails on the step "Minifying UMD bundles".

```
> @ngrx/platform@4.0.0 example:start /Applications/MAMP/htdocs/tmp/ngrx-platform
> yarn run build && yarn run cli -- serve

yarn run v0.27.5
$ ts-node ./build/index.ts
✔ Removing "./dist" Folder
✔ Compiling packages with NGC
✔ Bundling FESMs
✔ Down-leveling FESMs to ES5
✔ Creating UMD Bundles
✔ Renaming package entry files
✔ Cleaning TypeScript files
✔ Removing remaining sourcemap files
✔ Copying type definition files
✖ Minifying UMD bundles
{ Error: Command failed: /Applications/MAMP/htdocs/tmp/ngrx-platform/node_modules/.bin/uglifyjs -c -m --screw-ie8 --comments -o ./dist/store/bundles/store.umd.min.js --source-map ./dist/store/bundles/store.umd.min.js.map --source-map-include-sources ./dist/store/bundles/store.umd.js --in-source-map ./dist/store/bundles/store.umd.js.map
INFO: Using file from the input source map: store.umd.js
(node:79127) DeprecationWarning: util.error is deprecated. Use console.error instead.
/Applications/MAMP/htdocs/tmp/ngrx-platform/node_modules/directory-encoder/node_modules/uglify-js/bin/uglifyjs:226
            sys.error("ERROR: can't read file: " + filename);
                                                   ^

ReferenceError: filename is not defined
    at ReadFileContext.callback (/Applications/MAMP/htdocs/tmp/ngrx-platform/node_modules/directory-encoder/node_modules/uglify-js/bin/uglifyjs:226:52)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:365:13)

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/Applications/MAMP/htdocs/tmp/ngrx-platform/node_modules/.bin/uglifyjs -c -m --screw-ie8 --comments -o ./dist/store/bundles/store.umd.min.js --source-map ./dist/store/bundles/store.umd.min.js.map --source-map-include-sources ./dist/store/bundles/store.umd.js --in-source-map ./dist/store/bundles/store.umd.js.map' }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ngrx/platform@4.0.0 example:start: `yarn run build && yarn run cli -- serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ngrx/platform@4.0.0 example:start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/johe/.npm/_logs/2017-08-07T13_13_44_926Z-debug.log```

## Expected behavior:
Running the example without a crash.
```

## Minimal reproduction of the problem with instructions:
```
yarn
npm run example:start
```

## Version of affected browser(s),operating system(s), npm, node and ngrx:
Mac OS 10.11.6
node 6.9.4
npm 5.3.0
yarn 0.27.5

**Comment by PhillipZada** [comment]
Have you tried updating your node version?

**Comment by tja4472** [comment]
- Remove node_modules
- Install with npm 5.3 or yarn 0.28.4.
```
PS C:\VSCode\ngrx\git-hub\platform> yarn run example:start
yarn run v0.28.4
$ yarn run build && yarn run cli -- serve
√ Removing "./dist" Folder
√ Compiling packages with NGC
√ Bundling FESMs
√ Down-leveling FESMs to ES5
√ Creating UMD Bundles
√ Renaming package entry files
√ Cleaning TypeScript files
√ Removing remaining sourcemap files
√ Copying type definition files
√ Minifying UMD bundles
√ Copying documents
√ Copying package.json files
√ Removing "./dist/packages" Folder
** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200 **
Hash: 6e6430fc16f17945f75d
Time: 36124ms
chunk    {0} 0.chunk.js, 0.chunk.js.map 68.8 kB {2} [rendered]
chunk    {1} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 307 kB {5} [initial] [rendered]
chunk    {2} main.bundle.js, main.bundle.js.map (main) 121 kB {4} [initial] [rendered]
chunk    {3} styles.bundle.js, styles.bundle.js.map (styles) 45.1 kB {5} [initial] [rendered]
chunk    {4} vendor.bundle.js, vendor.bundle.js.map (vendor) 4.48 MB [initial] [rendered]
chunk    {5} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]
webpack: Compiled successfully.
```
hth
Tim

**Comment by creat-or** [comment]
Thank you! Installing the packages with npm 5.3.0 worked :)
