### ISSUE TITLE
Can't build modules and example app that depends on them twice without ngcc related error

### ISSUE THREAD

**Issue by donohoea** [ngrx/platform#3054]
## Minimal reproduction of the bug/regression with instructions:

`nx run store:build --skip-nx-cache`    
`nx run example-app:build --skip-nx-cache`
`nx run store:build --skip-nx-cache`  
`nx run example-app:build --skip-nx-cache`

produces:

```
An error occurred during the build:
Error: Tried to overwrite C:/examples/platform/node_modules/@ngrx/store/src/actions_subject.d.ts.__ivy_ngcc_bak with an ngcc back up file, which is disallowed.     
    at NewEntryPointFileWriter.InPlaceFileWriter.writeFileAndBackup (C:\examples\platform\node_modules\@angular\compiler-cli\ngcc\src\writing\in_place_file_writer.js:58:27)
    at NewEntryPointFileWriter.writeFile (C:\examples\platform\node_modules\@angular\compiler-cli\ngcc\src\writing\new_entry_point_file_writer.js:128:53)
    at C:\examples\platform\node_modules\@angular\compiler-cli\ngcc\src\writing\new_entry_point_file_writer.js:47:69
    at Array.forEach (<anonymous>)
    at NewEntryPointFileWriter.writeBundle (C:\examples\platform\node_modules\@angular\compiler-cli\ngcc\src\writing\new_entry_point_file_writer.js:47:30)
    at writeBundle (C:\examples\platform\node_modules\@angular\compiler-cli\ngcc\src\execution\create_compile_function.js:58:36)
    at C:\examples\platform\node_modules\@angular\compiler-cli\ngcc\src\execution\create_compile_function.js:65:25
    at SingleProcessExecutorSync.SingleProcessorExecutorBase.doExecute (C:\examples\platform\node_modules\@angular\compiler-cli\ngcc\src\execution\single_process_executor.js:36:17)
    at C:\examples\platform\node_modules\@angular\compiler-cli\ngcc\src\execution\single_process_executor.js:57:59
    at SyncLocker.lock (C:\examples\platform\node_modules\@angular\compiler-cli\ngcc\src\locking\sync_locker.js:34:24)
    at SingleProcessExecutorSync.execute (C:\examples\platform\node_modules\@angular\compiler-cli\ngcc\src\execution\single_process_executor.js:57:27)
    at Object.mainNgcc (C:\examples\platform\node_modules\@angular\compiler-cli\ngcc\src\main.js:74:25)
    at Object.process (C:\examples\platform\node_modules\@angular\compiler-cli\ngcc\index.js:29:23)
    at NgccProcessor.processModule (C:\examples\platform\node_modules\@ngtools\webpack\src\ngcc_processor.js:163:16)
    at C:\examples\platform\node_modules\@ngtools\webpack\src\ivy\host.js:121:18
    at C:\examples\platform\node_modules\@ngtools\webpack\src\ivy\host.js:51:24
Tried to overwrite C:/examples/platform/node_modules/@ngrx/store/src/actions_subject.d.ts.__ivy_ngcc_bak with an ngcc back up file, which is disallowed.
```

## Expected behavior:

Successful second build.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

Run on ngrx/platform master branch.

## I would be willing to submit a PR to fix this issue

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by donohoea** [comment]
All subsequent attempts to build example-app fail but if you delete `node_modules/@ngrx` you can build a module once without causing issues but if a module gets built a second time attempts to build example-app or data-example-app fail.
