### ISSUE TITLE
Unhandled Promise rejection: No provider for Actions!

### ISSUE THREAD

**Issue by oleosjo** [ngrx/platform#323]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
</code></pre>

## What is the current behavior?
<pre><code>
zone.js:661 Unhandled Promise rejection: No provider for Actions! ; Zone: <root> ; Task: Promise.then ; Value: Error: No provider for Actions!
    at injectionError (core.es5.js:1169)
    at noProviderError (core.es5.js:1207)
    at ReflectiveInjector_.webpackJsonp.../../../core/@angular/core.es5.js.ReflectiveInjector_._throwOrNull (core.es5.js:2649)
    at ReflectiveInjector_.webpackJsonp.../../../core/@angular/core.es5.js.ReflectiveInjector_._getByKeyDefault (core.es5.js:2688)
    at ReflectiveInjector_.webpackJsonp.../../../core/@angular/core.es5.js.ReflectiveInjector_._getByKey (core.es5.js:2620)
    at ReflectiveInjector_.webpackJsonp.../../../core/@angular/core.es5.js.ReflectiveInjector_.get (core.es5.js:2489)
    at resolveNgModuleDep (core.es5.js:9481)
    at _createClass (core.es5.js:9532)
    at _createProviderInstance$1 (core.es5.js:9492)
    at initNgModule (core.es5.js:9446) Error: No provider for Actions!
    at injectionError (http://localhost:4200/vendor.bundle.js:89865:90)
    at noProviderError (http://localhost:4200/vendor.bundle.js:89903:12)
    at ReflectiveInjector_.webpackJsonp.../../../core/@angular/core.es5.js.ReflectiveInjector_._throwOrNull (http://localhost:4200/vendor.bundle.js:91345:19)
    at ReflectiveInjector_.webpackJsonp.../../../core/@angular/core.es5.js.ReflectiveInjector_._getByKeyDefault (http://localhost:4200/vendor.bundle.js:91384:25)
    at ReflectiveInjector_.webpackJsonp.../../../core/@angular/core.es5.js.ReflectiveInjector_._getByKey (http://localhost:4200/vendor.bundle.js:91316:25)
    at ReflectiveInjector_.webpackJsonp.../../../core/@angular/core.es5.js.ReflectiveInjector_.get (http://localhost:4200/vendor.bundle.js:91185:21)
    at resolveNgModuleDep (http://localhost:4200/vendor.bundle.js:98177:25)
    at _createClass (http://localhost:4200/vendor.bundle.js:98228:32)
    at _createProviderInstance$1 (http://localhost:4200/vendor.bundle.js:98188:26)
    at initNgModule (http://localhost:4200/vendor.bundle.js:98142:13)
</code></pre>

## Expected behavior:
Works

## Minimal reproduction of the problem with instructions:
<pre><code>
@NgModule({
  declarations: [
    AppComponent,
    AppContainerComponent,
  ],
  imports: [
    StoreModule.forRoot(reducers),
    NgrxQueryModule.forRoot(),
    EffectsModule.forRoot([
      LoginEffects,
      SignupEffects,
      ErrorEffects,
      SelectedEntitiesEffects,
      AlertEffects,
      GeocodeEffects
    ]),
    !environment.production ? StoreDevtoolsModule.instrument({ maxAge: 25 }) : [],
    BrowserAnimationsModule,
    NgxPopperModule,
    authHttpModule,
    RouterModule.forRoot(appRoutes),
    BrowserModule,
    CoreModule,
    DashboardModule,
    EventsModule,
    HotelsModule,
    PeopleModule,
    SharedModule,
    SignupModule,
    GroupsModule,
  ],
  providers: [
    { provide: XSRFStrategy, useFactory: xsrfFactory }
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
</code></pre>

After a recent `npm install`, I get this 'no provider for actions' error... I've checked and rechecked that the syntax for my module is correct. Any ideas? Thanks!

**Comment by oleosjo** [comment]
If I switch the location of 'NgrxQueryModule.forRoot()' I get the same error but with 'store' instead of 'actions'. Removing it, produces the same error.

**Comment by brandonroberts** [comment]
Will you provide a minimal reproduction of this in a repo? Its likely that you have two copies of ngrx libraries somewhere, so you're getting two different tokens for `Actions`. I tried the demo app from https://github.com/isaacplmann/ngrx-query and it worked fine.

**Comment by codecoster** [comment]
@oleosjo 
I seem to get the "store"-Related Error if I try to use @ngrx/effects in my Project. However, this seems to be somehow related to the latest Angular-CLI (v1.3.2).  If I downgrade to 1.3.1, it seems to work for me again.
Which version of Angular-CLi (if any) do you use?

**Comment by oleosjo** [comment]
@codecoster I'm using 1.2.7. I fixed my issue by removing the carets from my package.json file. So I may have done essentially what you did.
