### ISSUE TITLE
Schematics: --path does not necessarily have to hold the --module

### ISSUE THREAD

**Issue by moniuch** [ngrx/platform#3301]
A thing related to #3300 

I went to create a slice of state, using:

```
ng generate @ngrx/schematics:reducer

--name=myslice
--project=admin
--module=admin.module
--no-creators
--no-flat
--path=libs/admin/src/lib/_store
```

I wanted it to be created at the `--path` specified , as a sibling of the `_store/user` slice:

![image 2022-01-25 15-36-34](https://user-images.githubusercontent.com/681956/150997152-a9dd0890-fbfc-4cfd-83d5-05597110a5e4.png)

```
_store
  user
    // user stuff
  myslice
    // myslice stuff
```

Unfortunately, the schematics also rejected the `--path`, complaining that 
`Specified module path /libs/admin/src/lib/_store/admin.module does not exist`

Sure it does not. It is a sibling of the `--path` directory

```
_store
  user
  myslice
admin.module.ts
```

The assumption that the `--path` directory holds the `--module` should not be applied. 
Please allow any directory within the project to keep the store, don't use it to search for the module.

Unless there is a way to achieve what I describe, which I am missing.
 

## If accepted, I would be willing to submit a PR for this feature

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
`path` can contain a relative path, so you can go to the parent directory:

```
ng generate @ngrx/schematics:reducer

--name=myslice
--project=admin
--module=../admin.module
--no-creators
--no-flat
--path=libs/admin/src/lib/_store
```

**Comment by moniuch** [comment]
@timdeschryver Thanks for help! I think I am grasping the thing now. TBH I was lost in my own interpretation of the terminology - _slice_ vs _feature_. The term _feature_ in ngrx understanding is a complete set of reducers/effects/selectors/actions. You run a feature schematics so that you don't have to run them individually. To me, _feature_ was a term more related to a feature module, a concept/unit closer to a library or feature module, something that you bring into the store using `StoreModule.forFeature()`.

Because of that, I was reluctant to run feature schematics twice, because I didn't want two separate items in my StoreDevTools.

![image 2022-01-25 22-33-25](https://user-images.githubusercontent.com/681956/151063391-8708b8d8-1e7c-44a0-b7cf-84ef55fd8e32.png)

What I understand now is that when you want to create a complete (reducers/effects/selectors/actions) _slice_, you in fact have to run a _feature_ schematics. Then you combine all the reducers (`users` + `myslice`) together in a main reducer 

```
StoreModule.forFeature('admin', adminReducer);
```

and this is how the _features_ you created become _slices_ in StoreDevTools.

```
admin:
    users:
    myslice:
```

In order to combine the slice reducers together you use `--reducers` parameter.
...which is where I think I encountered a bug. (The file exists, the path is ok, but the file is empty - what should it contain? How do I rectify this situation?)

Error
    at insertAfterLastOccurrence (/Users/[...]/node_modules/@ngrx/schematics/schematics-core/utility/ast-utils.js:137:15)
    at insertImport (/Users/[...]/node_modules/@ngrx/schematics/schematics-core/utility/ast-utils.js:639:12)
    at /Users/[...]/node_modules/@ngrx/schematics/schematics-core/utility/ngrx-utils.js:69:58
    at MergeMapSubscriber.project (/Users/[...]/node_modules/@angular-devkit/schematics/src/rules/call.js:75:24)
    at MergeMapSubscriber._tryNext (/Users/[...]/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/operators/mergeMap.js:67:27)
    at MergeMapSubscriber._next (/Users/[...]/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/operators/mergeMap.js:57:18)
    at MergeMapSubscriber.Subscriber.next (/Users/[...]/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/Subscriber.js:66:18)
    at Observable._subscribe (/Users/[...]/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/util/subscribeToArray.js:5:20)
    at Observable._trySubscribe (/Users/[...]/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/Observable.js:44:25)
    at Observable.subscribe (/Users/[...]/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/Observable.js:30:22)

PS. I would appreciate if you could confirm my understanding (_slice_ vs _feature_) is now correct.
