### ISSUE TITLE
TypeError: Converting circular structure to JSON  --> starting at object with constructor 'TView' in Angular 12?

### ISSUE THREAD

**Issue by kapilSoni101** [ngrx/platform#3463]
### Minimal reproduction of the bug/regression with instructions

Hi Team,
I am working on angular 12 and hit post API but suddenly its got error in the console i don't use JSON.stringify in my function for calling POST API below.same thing  is working on the angular 8 version but why got error in the 12 version?
 i have shared all details regarding to above error?

> TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'TView'
    |     property 'blueprint' -> object with constructor 'LViewBlueprint'
    --- index 1 closes the circle
    at JSON.stringify (<anonymous>)
    at HttpRequest.serializeBody (http.js:834:25)
    at Observable._subscribe (http.js:1751:33)
    at Observable._trySubscribe (Observable.js:42:25)
    at Observable.subscribe (Observable.js:28:22)
    at DoOperator.call (tap.js:16:23)
    at Observable.subscribe (Observable.js:23:31)
    at subscribeToResult (subscribeToResult.js:9:23)
    at MergeMapSubscriber._innerSub (mergeMap.js:59:26)
    at MergeMapSubscriber._tryNext (mergeMap.js:53:14)

![image](https://user-images.githubusercontent.com/26578635/175023638-f7cbb50a-096b-4716-bbb1-f646d0ce673a.png)

### Minimal reproduction of the bug/regression with instructions

Directly call API

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

Angular-12.2.16
Node:16.9.0
OS-Chrome

### Other information

Team can you please me why

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by timdeschryver** [comment]
Please define more info.

- How's this related to NgRx?
- What NgRx version are you using?
- Create a reproduction to help us help you

**Comment by kapil26021994** [comment]
@timdeschryver no sir it's not related to NgRx .can you tell me what I do dor that for fix?

**Comment by kapilSoni101** [comment]
@timdeschryver i am not asking a question its a issue that is exist in my case
