### ISSUE TITLE
 NG0600: Writing to signals is not allowed in a `computed` or an `effect` by default. Use `allowSignalWrites` in the `CreateEffectOptions` to enable this inside effects.

### ISSUE THREAD

**Issue by albanx** [ngrx/platform#3891]
### Which @ngrx/* package(s) are the source of the bug?

store

### Minimal reproduction of the bug/regression with instructions

Hi team

Just updated to the latest angular 16, and my server side rendering start getting many errors like
```
ERROR RuntimeError: NG0600: Writing to signals is not allowed in a `computed` or an `effect` by default. Use `allowSignalWrites` in the `CreateEffectOptions` to enable this inside effects.
    at throwInvalidWriteToSignalErrorFn (./node_modules/@angular/core/fesm2022/core.mjs:26577:15)
    at throwInvalidWriteToSignalError (./node_modules/@angular/core/fesm2022/core.mjs:2547:5)
    at set (./node_modules/@angular/core/fesm2022/core.mjs:2582:13)
    at value (./node_modules/@angular/core/fesm2022/rxjs-interop.mjs:783:30)
    at next (./node_modules/rxjs/dist/cjs/internal/Subscriber.js:113:33)
    at _next (./node_modules/rxjs/dist/cjs/internal/Subscriber.js:80:26)
    at next (./node_modules/rxjs/dist/cjs/internal/Subscriber.js:51:18)
    at onNext (./node_modules/rxjs/dist/cjs/internal/operators/take.js:15:32)
    at _next (./node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:33:21)
    at OperatorSubscriber.Subscriber.next (./node_modules/rxjs/dist/cjs/internal/Subscriber.js:51:18) {
  code: 600
}
```

I do not use any of the new angular stuff like signals, just a standard angular project with ngrx.
The issue comes up only under specific conditions. See reproduction steps.

### Minimal reproduction of the bug/regression with instructions

1. Create an new angular 16 app
2. Add Angular universal
3. Add ngrx
4. Create a request interceptor that reads from the store some random value and clones the requests
5. Create a component that does a request and uses the async pipe to show the request results in the component

Only with the above condition I can get the above error. 
Workarounds so far:
not using the async pipe in the component, example if I replace this
```
this.req$ = this.http.get('https://cat-fact.herokuapp.com/facts');
....
<ul>
  <li *ngFor="let property of req$ | async" class="link-prop">
    
    <app-para [property]="property.text">{{property.text}}</app-para>
  </li>
</ul>
```
with

```
this.http.get('https://cat-fact.herokuapp.com/facts').subscribe(list => {
  listOfFacts = list;
});
....
<ul>
  <li *ngFor="let property of listOfFacts" class="link-prop">
    
    <app-para [property]="property.text">{{property.text}}</app-para>
  </li>
</ul>
```
The error disappears.

OR
If I remove the Store selection from the interceptor, the error disappears.

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

Ngrx: 16.0.0-rc.0
Angular: 16 
Node: 18.15

### Other information

Package.json

```
{
  "name": "ciam-spa-angular16",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test",
    "dev:ssr": "ng run ciam_spa_angular16:serve-ssr",
    "serve:ssr": "node dist/ciam_spa_angular16/server/main.js",
    "build:ssr": "ng build && ng run ciam_spa_angular16:server",
    "prerender": "ng run ciam_spa_angular16:prerender"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^16.0.0",
    "@angular/common": "^16.0.0",
    "@angular/compiler": "^16.0.0",
    "@angular/core": "^16.0.0",
    "@angular/forms": "^16.0.0",
    "@angular/platform-browser": "^16.0.0",
    "@angular/platform-browser-dynamic": "^16.0.0",
    "@angular/platform-server": "^16.0.0",
    "@angular/router": "^16.0.0",
    "@ngrx/effects": "^16.0.0-rc.0",
    "@ngrx/store": "^16.0.0-rc.0",
    "@nguniversal/express-engine": "^16.0.0",
    "express": "^4.15.2",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.13.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^16.0.0",
    "@angular/cli": "~16.0.0",
    "@angular/compiler-cli": "^16.0.0",
    "@nguniversal/builders": "^16.0.0",
    "@types/express": "^4.17.0",
    "@types/jasmine": "~4.3.0",
    "@types/node": "^14.15.0",
    "jasmine-core": "~4.6.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.2.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.0.0",
    "typescript": "~5.0.2"
  }
}
```

### Interceptor code
```
import { Injectable } from '@angular/core';
import {
  HttpEvent,
  HttpInterceptor,
  HttpHandler,
  HttpRequest,
  HttpErrorResponse,
} from '@angular/common/http';
import { Observable, throwError } from 'rxjs';
import { Store, createSelector } from '@ngrx/store';
import { switchMap, first } from 'rxjs/operators';

@Injectable()
export class RequestInterceptor implements HttpInterceptor {
  constructor(private store: Store<{ count: number }>) {}

  intercept(
    request: HttpRequest<any>,
    next: HttpHandler
  ): Observable<HttpEvent<any>> {
    return this.store.select('count').pipe(
      first(),
      switchMap((count, index) => {
        const cloneRequest = request.clone({
          setHeaders: {
            Authorization: `Bearer ${count}`,
            Accept: 'application/json;charset=UTF-8',
          },
        });
        return next.handle(cloneRequest);
      })
    );
  }
}
```

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by albanx** [comment]
I see. Well done and thank you

**Comment by tarekahsan709** [comment]
Updated to the 16.0.0 release still the issue persist and the workarounds not using the async pipe in the component works.
{
   "@ngrx/component-store": "16.0.0",
    "@ngrx/effects": "16.0.0",
    "@ngrx/entity": "16.0.0",
    "@ngrx/router-store": "16.0.0",
    "@ngrx/store": "16.0.0",
}

**Comment by albanx** [comment]
@tarekahsan709  Try clear the node_modules, after I updated the final version of ngrx I did not get anymore the error on the Server Side Rendering

**Comment by tarekahsan709** [comment]
@albanx unfortunately it didn't work in my case. I have tried by roll backing and it's working.

**Comment by albanx** [comment]
Do you have reproduction steps?

**Comment by ChsGitHubber** [comment]
The bug seems to be still existing. I've just migrated my project to angular 16.0.1 and ngrx 16.0.0

**Comment by markostanimirovic** [comment]
Check this comment: https://github.com/ngrx/platform/issues/3892#issuecomment-1542791068
