### ISSUE TITLE
NG0600: Writing to signals is not allowed in a `computed` or an `effect` by default

### ISSUE THREAD

**Issue by cesco69** [ngrx/platform#3932]
### Which @ngrx/* package(s) are the source of the bug?

store

### Minimal reproduction of the bug/regression with instructions

Sometimes, this error happen:

```
Error: NG0600: Writing to signals is not allowed in a `computed` or an `effect` by default. Use `allowSignalWrites` in the `CreateEffectOptions` to enable this inside effects.
    at core.mjs:26765:15
    at throwInvalidWriteToSignalError (core.mjs:2584:5)
    at WritableSignalImpl.set (core.mjs:2619:13)
    at Object.next (rxjs-interop.mjs:785:30)
    at ConsumerObserver.next (Subscriber.js:91:33)
    at SafeSubscriber._next (Subscriber.js:60:26)
    at SafeSubscriber.next (Subscriber.js:31:18)
    at map.js:7:24
    at OperatorSubscriber._next (OperatorSubscriber.js:13:21)
    at OperatorSubscriber.next (Subscriber.js:31:18)
    at Subject.js:34:30
    at errorContext (errorContext.js:19:9)
    at ReplaySubject.next (Subject.js:27:21)
    at ReplaySubject.next (ReplaySubject.js:22:15)
    at Object.next (ngrx-store-devtools.mjs:831:32)
```

Into the stacktrace the problem see from ngrx-store-devtools. If I don't import `StoreDevtoolsModule` the stack trace become:

```
Error: NG0600: Writing to signals is not allowed in a `computed` or an `effect` by default. Use `allowSignalWrites` in the `CreateEffectOptions` to enable this inside effects.
    at core.mjs:26765:15
    at throwInvalidWriteToSignalError (core.mjs:2584:5)
    at WritableSignalImpl.set (core.mjs:2619:13)
    at Object.next (rxjs-interop.mjs:785:30)
    at ConsumerObserver.next (Subscriber.js:91:33)
    at SafeSubscriber._next (Subscriber.js:60:26)
    at SafeSubscriber.next (Subscriber.js:31:18)
    at Subject.js:34:30
    at errorContext (errorContext.js:19:9)
    at State.next (Subject.js:27:21)
    at State.next (BehaviorSubject.js:24:15)
    at Object.next (ngrx-store.mjs:489:18)
    at ConsumerObserver.next (Subscriber.js:91:33)
    at SafeSubscriber._next (Subscriber.js:60:26)
    at SafeSubscriber.next (Subscriber.js:31:18)
```

### Minimal reproduction of the bug/regression with instructions

I have an HttpInterceptor for update a NetworkState for show/hide a spinner

```ts
import { Injectable } from '@angular/core';
import { HttpInterceptor, HttpRequest, HttpHandler, HttpEvent, HttpErrorResponse, HttpHeaders } from '@angular/common/http';
import { Observable, throwError } from 'rxjs';
import { finalize, catchError } from 'rxjs/operators';
import { Store } from '@ngrx/store';
import { NetworkState } from '../../store/reducers/network.reducer';
import * as networkActions from '../../store/actions/network.actions';

@Injectable({
  providedIn: 'root'
})
export class HttpInterceptorService implements HttpInterceptor {

  constructor(private store: Store<NetworkState>) { }

  intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {

    this.store.dispatch(networkActions.httpLoadingBegin());
    return next.handle(req).pipe(
      catchError((error: HttpErrorResponse) => {
        return throwError(() => error);
      }),
      finalize(() => {
        this.store.dispatch(networkActions.httpLoadingEnd());
      })
    );
  }

}
```

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

```json
"dependencies": {
    "@angular/animations": "^16.1.1",
    "@angular/cdk": "^16.1.1",
    "@angular/common": "^16.1.1",
    "@angular/compiler": "^16.1.1",
    "@angular/core": "^16.1.1",
    "@angular/forms": "^16.1.1",
    "@angular/material": "^16.1.1",
    "@angular/material-date-fns-adapter": "^16.1.1",
    "@angular/platform-browser": "^16.1.1",
    "@angular/platform-browser-dynamic": "^16.1.1",
    "@angular/router": "^16.1.1",
    "@ngneat/transloco": "^4.3.0",
    "@ngrx/effects": "^16.0.1",
    "@ngrx/entity": "^16.0.1",
    "@ngrx/store": "^16.0.1",
    "@ngrx/store-devtools": "^16.0.1",
    "broadcastchannel-polyfill": "^1.0.1",
    "date-fns": "^2.30.0",
    "dayjs": "^1.11.8",
    "devextreme": "^23.1.3",
    "devextreme-angular": "^23.1.3",
    "humanize-duration": "^3.28.0",
    "intro.js": "^7.0.1",
    "lodash.isequal": "^4.5.0",
    "ng-table-virtual-scroll": "1.6.0",
    "ngx-color-picker": "^14.0.0",
    "pako": "^2.1.0",
    "rxjs": "~7.8.1",
    "socket.io-client": "^4.6.2",
    "tslib": "^2.5.3",
    "zone.js": "~0.13.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^16.1.0",
    "@angular-eslint/builder": "^16.0.3",
    "@angular-eslint/eslint-plugin": "^16.0.3",
    "@angular-eslint/eslint-plugin-template": "^16.0.3",
    "@angular-eslint/schematics": "^16.0.3",
    "@angular-eslint/template-parser": "^16.0.3",
    "@angular/cli": "~16.1.0",
    "@angular/compiler-cli": "^16.1.1",
    "@rx-angular/eslint-plugin": "^1.0.0",
    "@types/intro.js": "^5.1.1",
    "@types/jasmine": "~4.3.2",
    "@types/node": "^20.3.1",
    "@types/pako": "^2.0.0",
    "@types/wicg-file-system-access": "^2020.9.6",
    "@typescript-eslint/eslint-plugin": "^5.59.11",
    "@typescript-eslint/parser": "^5.59.11",
    "eslint": "^8.42.0",
    "jasmine-core": "~5.0.1",
    "karma": "~6.4.2",
    "karma-chrome-launcher": "~3.2.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.1.0",
    "sonarqube-scanner": "^3.0.1",
    "typescript": "~5.1.3"
  },
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by timdeschryver** [comment]
See #3891 and #3892

**Comment by nigrosimone** [comment]
@timdeschryver https://github.com/ngrx/platform/issues/3891 and https://github.com/ngrx/platform/issues/3892 talk about update Angular at >16.0.4 and NGRX at 16.0.1. The user has:

```
 "@angular/core": "^16.1.1",
 "@ngrx/store": "^16.0.1",
```
I have the same issue (the error become from an HttpInterceptor ) with all update installed, eg.:

```ts
@Injectable({
  providedIn: 'root'
})
export class HttpInterceptorService implements HttpInterceptor {

  constructor(private store: Store<NetworkState>) { }

  intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    this.store.dispatch(actions.someAction()); // <--- This cause the error
    return next.handle(req);
  }

}
```

Exactly, how fix that?
Thanks!

**Comment by cesco69** [comment]
The fix is

```ts
@Injectable({
  providedIn: 'root'
})
export class HttpInterceptorService implements HttpInterceptor {

  constructor(private store: Store) { }

  intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    // this.store.dispatch(actions.someAction()); // <--- This cause the error
    asapScheduler.schedule(() => this.store.dispatch(actions.someAction())); // the fix
    return next.handle(req);
  }

}
```
