### ISSUE TITLE
feat(@ngrx/data): register in Angular custom DataService and EntityService standalone project

### ISSUE THREAD

**Issue by cretara** [ngrx/platform#3934]
### Which @ngrx/* package(s) are relevant/related to the feature request?

@ngrx/data

### Information

Hello everyone,
in previous version of Angular without standalone, we had to create a module in order to create custom DataService and EntityService in order to customize API calls like following one

Let's assume we have an entity definition like following one
post.ts
```typescript
export const entityMetadataMap: EntityMetadataMap = {
  Post: {},
}; export const entityMetadataMap: EntityDataModuleConfig = {
    entityMetadata: entityMetadataMap
};
```

I need to create a custom DataService associated to that entity in order to override default API calls, beacause of non-REST like API in backend
post-data.service.ts
```typescript
@Injectable()
export class PostDataService extends DefaultDataService<Post> {
  constructor(
    http: HttpClient,
    httpUrlGenerator: HttpUrlGenerator,
    private postService: PostService
  ) {
    super('Post', http, httpUrlGenerator);
  }   override getAll(): Observable<Post[]> {
    return this.postService.getPostsFromAPI();
  }
}
```

post-entity.service.ts
```typescript
@Injectable({ providedIn: 'root' })
export class PostEntityService extends EntityCollectionServiceBase<Post> {
  constructor(serviceElementsFactory: EntityCollectionServiceElementsFactory) {
    super('Post', serviceElementsFactory);
  }
}
```

In order to instantiate PostDataService, we need to register custom DataService

generic.module.ts
```typescript
@NgModule({
  providers: [PostDataService],
})
export class GenericModule {
  constructor(
    entityDataService: EntityDataService,
    postDataService: PostDataService
  ) {
    entityDataService.registerService('Post', postDataService);
  }
}
```

I would like to know if there is an alternative of this approach, or if there is already an API for standalone projects link following one in Stackblitz: https://stackblitz-starters-8r6uuz.stackblitz.io

Best regards

### Describe any alternatives/workarounds you're currently using

Would be great if in main.ts or in any route we could write like following:
```typescript
export const appConfig: ApplicationConfig = {
  providers: [
    provideRouter(appRoutes),
    provideHttpClient(),
    provideStore(),
    provideEffects(),
    provideDataService(PostDataService)
  ]
};
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by markostanimirovic** [comment]
Hi @cretara,

For standalone apps, you can use `ENVIRONMENT_INITIALIZER` instead of the NgModule constructor:

```ts
export const appConfig: ApplicationConfig = {
  providers: [
    provideRouter(appRoutes),
    provideHttpClient(),
    provideStore(),
    provideEffects(),
    PostDataService,
    {
      provide: ENVIRONMENT_INITIALIZER,
      useValue() {
        const entityDataService = inject(EntityDataService);
        const postDataService = inject(PostDataService);

        entityDataService.registerService('Post', postDataService);
      },
      multi: true,
    },
  ]
};
```

**Comment by cretara** [comment]
> Hi @cretara,
> 
> For standalone apps, you can use `ENVIRONMENT_INITIALIZER` instead of the NgModule constructor:
> 
> ```ts
> export const appConfig: ApplicationConfig = {
>   providers: [
>     provideRouter(appRoutes),
>     provideHttpClient(),
>     provideStore(),
>     provideEffects(),
>     PostDataService,
>     {
>       provide: ENVIRONMENT_INITIALIZER,
>       useValue() {
>         const entityDataService = inject(EntityDataService);
>         const postDataService = inject(PostDataService);
> 
>         entityDataService.registerService('Post', postDataService);
>       },
>       multi: true,
>     },
>   ]
> };
> ```

Thanks @markostanimirovic , i tried to add this to my simple app, but i get following error

```
NullInjectorError: NullInjectorError: No provider for EntityDataService!
    at NullInjector.get (core.mjs:8746:27)
    at R3Injector.get (core.mjs:9175:33)
    at R3Injector.get (core.mjs:9175:33)
    at injectInjectorOnly (core.mjs:651:33)
    at ɵɵinject (core.mjs:655:60)
    at inject (core.mjs:738:12)
    at useValue (app.config.ts:24:41)
    at R3Injector.resolveInjectorInitializers (core.mjs:9213:17)
    at core.mjs:26753:25
    at _ZoneDelegate.invoke (zone.js:368:26)
(anonymous) @ main.ts:12
invoke @ zone.js:368
run @ zone.js:127
(anonymous) @ zone.js:1257
invokeTask @ zone.js:402
runTask @ zone.js:171
drainMicroTaskQueue @ zone.js:581
Promise.then (async)
nativeScheduleMicroTask @ zone.js:557
scheduleMicroTask @ zone.js:568
resolvePromise @ zone.js:1209
reject @ zone.js:1279
internalCreateApplication @ core.mjs:26791
bootstrapApplication @ platform-browser.mjs:1027
4431 @ main.ts:11
__webpack_require__ @ bootstrap:19
__webpack_exec__ @ main.ts:12
(anonymous) @ main.ts:12
__webpack_require__.O @ chunk loaded:23
(anonymous) @ main.ts:12
webpackJsonpCallback @ jsonp chunk loading:34
(anonymous) @ main.js:2
Show 15 more frames
```

If i try to add EntityDataService in providers like this
```typescript
export const appConfig: ApplicationConfig = {
  providers: [
    provideRouter(appRoutes),
    provideHttpClient(),
    provideStore(),
    provideEffects(),
    PostDataService,
    EntityDataService,
    {
      provide: ENVIRONMENT_INITIALIZER,
      useValue() {
        const entityDataService = inject(EntityDataService);
        const postDataService = inject(PostDataService);
        entityDataService.registerService('Post', postDataService);
      },
      multi: true,
    },
  ],
};
```

i get following error
```
main.ts:12 NullInjectorError: NullInjectorError: No provider for DefaultDataServiceFactory!
    at NullInjector.get (core.mjs:8746:27)
    at R3Injector.get (core.mjs:9175:33)
    at R3Injector.get (core.mjs:9175:33)
    at injectInjectorOnly (core.mjs:651:33)
    at Module.ɵɵinject (core.mjs:655:60)
    at Object.EntityDataService_Factory [as factory] (ngrx-data.mjs:58:84)
    at R3Injector.hydrate (core.mjs:9276:35)
    at R3Injector.get (core.mjs:9164:33)
    at injectInjectorOnly (core.mjs:651:33)
    at ɵɵinject (core.mjs:655:60)
(anonymous) @ main.ts:12
invoke @ zone.js:368
run @ zone.js:127
(anonymous) @ zone.js:1257
invokeTask @ zone.js:402
runTask @ zone.js:171
drainMicroTaskQueue @ zone.js:581
Promise.then (async)
nativeScheduleMicroTask @ zone.js:557
scheduleMicroTask @ zone.js:568
resolvePromise @ zone.js:1209
reject @ zone.js:1279
internalCreateApplication @ core.mjs:26791
bootstrapApplication @ platform-browser.mjs:1027
4431 @ main.ts:11
__webpack_require__ @ bootstrap:19
__webpack_exec__ @ main.ts:12
(anonymous) @ main.ts:12
__webpack_require__.O @ chunk loaded:23
(anonymous) @ main.ts:12
webpackJsonpCallback @ jsonp chunk loading:34
(anonymous) @ main.js:2
Show 15 more frames
```

Can u help to fix this please?

**Comment by markostanimirovic** [comment]
You need to use [`provideEntityData`](https://ngrx.io/guide/data#using-the-standalone-api):

```ts
export const appConfig: ApplicationConfig = {
  providers: [
    provideRouter(appRoutes),
    provideHttpClient(),
    provideStore(),
    provideEffects(),
    provideEntityData(entityConfig, withEffects()),
    PostDataService,
    EntityDataService,
    {
      provide: ENVIRONMENT_INITIALIZER,
      useValue() {
        const entityDataService = inject(EntityDataService);
        const postDataService = inject(PostDataService);
        entityDataService.registerService('Post', postDataService);
      },
      multi: true,
    },
  ],
};
```

**Comment by cretara** [comment]
> 

Thanks a lot, i missed this step.

I suggest to update docs with both guides to create an "Hello world" in standalone and module application examples step by step: i can submit a PR, too

**Comment by markostanimirovic** [comment]
I'm going to close this feature request because NgRx Data is in maintenance mode. Improvements/new features won't be added anymore.
