### ISSUE TITLE
example-app fails during build 

### ISSUE THREAD

**Issue by lorenjerickson** [ngrx/platform#432]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

when attemping to build/run the example app the minify/uglify step fails with the following error: 

```
lorenerickson@Lorens-MBP:~/Source/ngrx-platform$ yarn run example:start
yarn run v0.27.5
$ yarn run build && yarn run cli -- serve
✔ Removing "./dist" Folder
✔ Compiling packages with NGC
✔ Bundling FESMs
✔ Down-leveling FESMs to ES5
✔ Creating UMD Bundles
✔ Renaming package entry files
✔ Cleaning TypeScript files
✔ Removing remaining sourcemap files
✔ Copying type definition files
✖ Minifying UMD bundles
{ Error: Command failed: "/Users/lorenerickson/Source/ngrx-platform/node_modules/.bin/uglifyjs" -c -m --screw-ie8 --comments -o ./dist/store/bundles/store.umd.min.js --source-map ./dist/store/bundles/store.umd.min.js.map --source-map-include-sources ./dist/store/bundles/store.umd.js --in-source-map ./dist/store/bundles/store.umd.js.map
INFO: Using file from the input source map: store.umd.js
(node:1808) DeprecationWarning: util.error is deprecated. Use console.error instead.
/Users/lorenerickson/Source/ngrx-platform/node_modules/directory-encoder/node_modules/uglify-js/bin/uglifyjs:226
            sys.error("ERROR: can't read file: " + filename);
                                                   ^

ReferenceError: filename is not defined
    at ReadFileContext.callback (/Users/lorenerickson/Source/ngrx-platform/node_modules/directory-encoder/node_modules/uglify-js/bin/uglifyjs:226:52)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:366:13)

    at ChildProcess.exithandler (child_process.js:198:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: '"/Users/lorenerickson/Source/ngrx-platform/node_modules/.bin/uglifyjs" -c -m --screw-ie8 --comments -o ./dist/store/bundles/store.umd.min.js --source-map ./dist/store/bundles/store.umd.min.js.map --source-map-include-sources ./dist/store/bundles/store.umd.js --in-source-map ./dist/store/bundles/store.umd.js.map' }
error Command failed with exit code 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Expected behavior:

Example app should build/run out of the box.

## Minimal reproduction of the problem with instructions:

1. clone the ngrx/platform repo
2. follow the instructions in the README.md under ./example-app for building and running the app.
3. observe the error above.  

## Other information:

```
lorenerickson@Lorens-MBP:~/Source/ngrx-platform$ ng -v
Your global Angular CLI version (1.3.1) is greater than your local
version (1.2.1). The local Angular CLI version is used.

To disable this warning use "ng set --global warnings.versionMismatch=false".
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.2.1
node: 6.11.2
os: darwin x64
@angular/cdk: 2.0.0-beta.8
@angular/animations: 4.2.6
@angular/cli: 1.2.1
@angular/common: 4.2.6
@angular/compiler: 4.2.6
@angular/compiler-cli: 4.2.6
@angular/core: 4.2.6
@angular/forms: 4.2.6
@angular/http: 4.2.6
@angular/material: 2.0.0-beta.8
@angular/platform-browser: 4.2.6
@angular/platform-browser-dynamic: 4.2.6
@angular/platform-server: 4.2.6
@angular/router: 4.2.6
lorenerickson@Lorens-MBP:~/Source/ngrx-platform$ tsc -v
Version 2.5.2
```

**Comment by brandonroberts** [comment]
I would suggest updating your version of node/npm. If you need further support, please use the support channel https://gitter.im/ngrx/platform
