### ISSUE TITLE
Rule @ngrx/use-effects-lifecycle-interface crashes with error TypeError: Cannot read properties of undefined (reading 'range')

### ISSUE THREAD

**Issue by zilia-gmethot** [ngrx/platform#4429]
### Which @ngrx/* package(s) are the source of the bug?

eslint-plugin

### Minimal reproduction of the bug/regression with instructions

**Repository**: https://github.com/zilia-gmethot/ngrx-eslint-crash-reproduction

**Instructions**
1. Clone the repository
2. Run ESLint with `npx eslint .` You should obtain the following error:

```
Oops! Something went wrong! :(

ESLint: 8.57.0

TypeError: Cannot read properties of undefined (reading 'range')
Occurred while linting /home/gabriel/dev/ngrx-eslint-crash-reproduction/src/effect.ts:9
Rule: "@ngrx/use-effects-lifecycle-interface"
    at Object.insertTextAfter (/home/gabriel/dev/ngrx-eslint-crash-reproduction/node_modules/eslint/lib/linter/rule-fixer.js:49:54)
    at Object.fix (/home/gabriel/dev/ngrx-eslint-crash-reproduction/node_modules/@ngrx/eslint-plugin/src/rules/effects/use-effects-lifecycle-interface.js:68:35)
    at normalizeFixes (/home/gabriel/dev/ngrx-eslint-crash-reproduction/node_modules/eslint/lib/linter/report-translator.js:194:28)
    at /home/gabriel/dev/ngrx-eslint-crash-reproduction/node_modules/eslint/lib/linter/report-translator.js:365:49
    at Object.report (/home/gabriel/dev/ngrx-eslint-crash-reproduction/node_modules/eslint/lib/linter/linter.js:1047:41)
    at _a.<computed> (/home/gabriel/dev/ngrx-eslint-crash-reproduction/node_modules/@ngrx/eslint-plugin/src/rules/effects/use-effects-lifecycle-interface.js:64:25)
    at ruleErrorHandler (/home/gabriel/dev/ngrx-eslint-crash-reproduction/node_modules/eslint/lib/linter/linter.js:1076:28)
    at /home/gabriel/dev/ngrx-eslint-crash-reproduction/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/home/gabriel/dev/ngrx-eslint-crash-reproduction/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
```

### Expected behavior

An error for the rule `@ngrx/use-effects-lifecycle-interface` shouldn't crash ESLint.

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

NgRx: 17.1.1
Angular 17.1.1
Node.js: 20.12.0
ESLint: 8.57.0

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by timdeschryver** [comment]
Hi, sorry for the inconvenience.
This should be resolved in NgRx v18.
If that's not the case, feel free to reopen this issue.
