### ISSUE TITLE
ReferenceError: filename is not defined when building

### ISSUE THREAD

**Issue by bknill** [ngrx/platform#464]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

Error when attempting to build and run

## Expected behavior:

IT builds and run

## Minimal reproduction of the problem with instructions:

Cloned repo, followed install instuctions 

## Other information:

$ yarn run build && yarn run cli -- serve
yarn run v0.27.5
$ ts-node ./build/index.ts
√ Removing "./dist" Folder
√ Compiling packages with NGC
√ Bundling FESMs
√ Down-leveling FESMs to ES5
√ Creating UMD Bundles
√ Renaming package entry files
√ Cleaning TypeScript files
√ Removing remaining sourcemap files
√ Copying type definition files
× Minifying UMD bundles
{ Error: Command failed: "C:\workspace\showhowAdmin\platform\node_modules\.bin\uglifyjs" -c -m --screw-ie8 --comments -o ./dist/store/bundles/store.umd.min.js --source-map ./dist/store/bundles/store.umd.min.js.map --source-map-include-sources ./dist/store/bundles/store.umd.js --in-source-map ./dist/store/bundles/store.umd.js.map
INFO: Using file from the input source map: store.umd.js
(node:19460) DeprecationWarning: util.error is deprecated. Use console.error instead.
C:\workspace\showhowAdmin\platform\node_modules\directory-encoder\node_modules\uglify-js\bin\uglifyjs:226
            sys.error("ERROR: can't read file: " + filename);
                                                   ^

ReferenceError: filename is not defined
    at ReadFileContext.callback (C:\workspace\showhowAdmin\platform\node_modules\directory-encoder\node_modules\uglify-js\bin\uglifyjs:226:52)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:366:13)

    at ChildProcess.exithandler (child_process.js:198:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: '"C:\\workspace\\showhowAdmin\\platform\\node_modules\\.bin\\uglifyjs" -c -m --screw-ie8 --comments -o ./dist/store/bundles/store.umd.min.js --source-map ./dist/store/bundles/store.umd.min.js.map --source-map-include-sources ./dist/store/bundles/store.umd.js --in-source-map ./dist/store/bundles/store.umd.js.map' }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by bknill** [comment]
Found the other answers in closed, out of date NPM
