### ISSUE TITLE
Type 'string' cannot be used to index type 'EffectsMetadata<T>'

### ISSUE THREAD

**Issue by jupiter101** [ngrx/platform#518]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
Effects module masterbranch does not compile 
<pre><code>
{ Error: Command failed: "D:\dev\js\angular\platform\node_modules\.bin\ngc" -p ./modules/effects/tsconfig-build.json
Error at D:/dev/js/angular/platform/modules/effects/src/effects_metadata.ts:56:5: Type 'string' cannot be used to index type 'EffectsMetadata<T>'.

    at ChildProcess.exithandler (child_process.js:204:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: '"D:\\dev\\js\\angular\\platform\\node_modules\\.bin\\ngc" -p ./modules/effects/tsconfig-build.json' }
</code></pre>
failing statement: metadata[propertyName] = { dispatch };

## Expected behavior:
Compile

## Minimal reproduction of the problem with instructions:
1. Checkout master
2. npm install
3. npm run build

## Version of affected browser(s),operating system(s), npm, node and ngrx:
win7, node v6.10.3, npm 3.10.10, ngrx/platform (master)

**Comment by jupiter101** [comment]
okay compiles with
1. Checkout master
2. npm install
3. npm run clean
4. npm run build
but run in a different error when building
<code><pre>
{ Error: Command failed: "D:\dev\js\angular\platform\node_modules\.bin\uglifyjs" -c -m --screw-ie8 --comments -o ./dist/store/bundles/store.umd.min.js --source-map ./dist/store/bundles/store.umd.min.j
s.map --source-map-include-sources ./dist/store/bundles/store.umd.js --in-source-map ./dist/store/bundles/store.umd.js.map
INFO: Using file from the input source map: store.umd.js
(node:40128) DeprecationWarning: util.error is deprecated. Use console.error instead.
D:\dev\js\angular\platform\node_modules\directory-encoder\node_modules\uglify-js\bin\uglifyjs:226
            sys.error("ERROR: can't read file: " + filename);
                                                   ^

ReferenceError: filename is not defined
    at ReadFileContext.callback (D:\dev\js\angular\platform\node_modules\directory-encoder\node_modules\uglify-js\bin\uglifyjs:226:52)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:366:13)

    at ChildProcess.exithandler (child_process.js:204:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: '"D:\\dev\\js\\angular\\platform\\node_modules\\.bin\\uglifyjs" -c -m --screw-ie8 --comments -o ./dist/store/bundles/store.umd.min.js --source-map ./dist/store/bundles/store.umd.min.js.map --so
urce-map-include-sources ./dist/store/bundles/store.umd.js --in-source-map ./dist/store/bundles/store.umd.js.map' }

</code></pre>

**Comment by jupiter101** [comment]
finally now in #519
