### ISSUE TITLE
Example App Wont Start

### ISSUE THREAD

**Issue by GreenhornDeveloper** [ngrx/platform#543]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

Example app wont start after running `build` command
```
yarn run v0.27.5
$ yarn run build && yarn run cli -- serve
√ Removing "./dist" Folder
√ Compiling packages with NGC
√ Bundling FESMs
√ Down-leveling FESMs to ES5
√ Creating UMD Bundles
√ Renaming package entry files
√ Cleaning TypeScript files
√ Removing remaining sourcemap files
√ Copying type definition files
x Minifying UMD bundles
{ Error: Command failed: "D:\ngrxTest\platform\node_modules\.bin\uglifyjs" -c -m --screw-ie8 --comments -o ./dist/entity/bundles/entity.umd.min.js --source-map ./dist/entity/bundles/entity.umd
.min.js.map --source-map-include-sources ./dist/entity/bundles/entity.umd.js --in-source-map ./dist/entity/bundles/entity.umd.js.map
INFO: Using file from the input source map: entity.umd.js
(node:7720) DeprecationWarning: util.error is deprecated. Use console.error instead.
D:\ngrxTest\platform\node_modules\directory-encoder\node_modules\uglify-js\bin\uglifyjs:226
            sys.error("ERROR: can't read file: " + filename);
                                                   ^

ReferenceError: filename is not defined
    at ReadFileContext.callback (D:\ngrxTest\platform\node_modules\directory-encoder\node_modules\uglify-js\bin\uglifyjs:226:52)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:366:13)

    at ChildProcess.exithandler (child_process.js:198:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: '"D:\\ngrxTest\\platform\\node_modules\\.bin\\uglifyjs" -c -m --screw-ie8 --comments -o ./dist/entity/bundles/entity.umd.min.js --source-map ./dist/entity/bundles/entity.umd.min.js.map
--source-map-include-sources ./dist/entity/bundles/entity.umd.js --in-source-map ./dist/entity/bundles/entity.umd.js.map' }
error Command failed with exit code 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
## Expected behavior:

Expected to see the app running on http://localhost:4200/

## Minimal reproduction of the problem with instructions:

I cloned the repo and followed the install instructions from the [README](https://github.com/ngrx/platform/blob/master/example-app/README.md)
## Version of affected browser(s),operating system(s), npm, node and ngrx:
Yarn:  0.27.5
Node: 6.11.2
Npm: 3.10.10
ngrx:  4.0.0

**Comment by ccpony** [comment]
+1

**Comment by brandonroberts** [comment]
You need to update your npm version

**Comment by ccpony** [comment]
Updated npm to ver 5.5.1.  Exact same error.  Please re-open.

**Comment by krjordan** [comment]
You should update your yarn version as well, since the scripts inside the `package.json` uses yarn to run the commands.
