### ISSUE TITLE
TypeError DevTools with StoreRouter

### ISSUE THREAD

**Issue by csutorasr** [ngrx/platform#60]
If I use the `StoreDevtoolsModule` and `StoreRouterConnectingModule` side by side I get the following error:

```
Unhandled Promise rejection: Cannot read property 'next' of undefined ; Zone: <root> ; Task: Promise.then ; Value:
TypeError: Cannot read property 'next' of undefined
TypeError: Cannot read property 'next' of undefined
    at ReducerManager.webpackJsonp.../../../../@ngrx/store/@ngrx/store.es5.js.ReducerManager.updateReducers (http://localhost:4200/vendor.bundle.js:1666:24)
    at ReducerManager.webpackJsonp.../../../../@ngrx/store/@ngrx/store.es5.js.ReducerManager.addReducer (http://localhost:4200/vendor.bundle.js:1650:14)
    at ReducerManager.webpackJsonp.../../../../@ngrx/store/@ngrx/store.es5.js.ReducerManager.addFeature (http://localhost:4200/vendor.bundle.js:1633:14)
    at http://localhost:4200/vendor.bundle.js:1993:69
    at Array.forEach (<anonymous>)
    at new StoreFeatureModule (http://localhost:4200/vendor.bundle.js:1993:18)
    at _createClass (http://localhost:4200/vendor.bundle.js:80913:17)
    at _createProviderInstance$1 (http://localhost:4200/vendor.bundle.js:80881:26)
    at initNgModule (http://localhost:4200/vendor.bundle.js:80835:13)
    at new NgModuleRef_ (http://localhost:4200/vendor.bundle.js:81943:9)
```

If I use only one of them it is working. With using only devtools I can debug. I couldn't really test if the router connector is working without the devtools. I tried to change the order of the modules in the `import` part of the main module, but none of them worked.

**Comment by bfricka** [comment]
You should probably add your best attempt at minimum code required to reproduce this (along w/ info on your dependency versions, etc)

**Comment by csutorasr** [comment]
Refreshing to the newest nightly solved the problem.
